### ISSUE TITLE
package.json postinstall error

### ISSUE THREAD

**Issue by nadeemkhedr** [bsalex/angular-loading-overlay#5]
postinstall runs `typings install`
this will not work if i don't have `typings` globally installed on my machine,

**Comment by bsalex** [comment]
Sure, thanks, missed that.
This is now fixed in master. 
e3149e463f4fcfb8e2e9e59d35ac0551bf9849a1

**Comment by bsalex** [comment]
[v1.1.1](https://github.com/bsalex/angular-loading-overlay/releases/tag/v1.1.1)
was released with the fix.
